# Local Development Container and Stack
#
# devc
# - Builds devcontainer Dockerfile image
# - VSCode devcontainer configuration
#
# postgres
# - runs PostgreSQL container
# - mounts pgdb-data as data volume
#
# adminer
# - runs adminer container
# - adminer accessible on port 8080
#
version: "3"
services:
  devc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_ZSH: 'true'
        UPGRADE_PACKAGES: 'true'
        VARIANT: 1.12-slim

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use environment configuration file for the dev container environment.
    env_file:
      - ../.env.local

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: host

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    volumes:
      - ..:/workspace:cached

  postgres:
    environment:
      POSTGRES_PASSWORD: password
    image: postgres
    network_mode: host
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - pgdb-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    network_mode: host
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  pgdb-data:
